### ISSUE TITLE
Error in sampling the template from uniform distribution?

### ISSUE THREAD

**Issue by amtsak** [yiqings/RandStainNA#2]
Thanks for making the code available for this.
Looking through the RandStainNA implementation I was wondering if there is a typo here: https://github.com/yiqings/RandStainNA/blob/master/randstainna.py#L153

```
tar_std = np.random.uniform(
    low=self.channel_avgs.avg[idx] - 3 * self.channel_avgs.std[idx],
    high=self.channel_avgs.avg[idx] + 3 * self.channel_avgs.std[idx],
)
```

Shouldn't this be?
```
tar_std = np.random.uniform(
    low=self.channel_stds.avg[idx] - 3 * self.channel_stds.std[idx],
    high=self.channel_stds.avg[idx] + 3 * self.channel_stds.std[idx],
)
```

**Comment by yiqings** [comment]
@amtsak Hi Anna. Exactly, you are correct. Thanks so much for pointing out the typo. We have fixed it already.
