### ISSUE TITLE
unrealistic aumentation

### ISSUE THREAD

**Issue by innocence0206** [yiqings/RandStainNA#6]
Thanks for your great work!
I run the datasets_statistics.py, produce the .yaml and apply RandStainNA to my own dataset, but I find most augmented images are not so realistic, could you give me some advice on how to adjust the parameters？ 
augmented：
![6_32](https://github.com/yiqings/RandStainNA/assets/60682243/bc7e584c-2a73-4ee4-98da-a3278092700a)
![6_51](https://github.com/yiqings/RandStainNA/assets/60682243/a3aeda63-05dc-4443-a98d-62bd840c1ce0)
origin：
![6_32](https://github.com/yiqings/RandStainNA/assets/60682243/6cd8fcd9-613e-49e3-b710-16e77c910de1)
![6_51](https://github.com/yiqings/RandStainNA/assets/60682243/cac638f3-5d1d-4e61-964e-086f2ede2fa6)

**Comment by maxmal1** [comment]
Any follow-up on this?
